### ISSUE TITLE
On Hide callback

### ISSUE THREAD

**Issue by afk-mario** [macvogelsang/pd-options#10]
Replaced my debug menu with this, it's so much cleaner I like it a lot!, one thing I'm missing is a callback when the menu hides, currently I need to pause/unpause the game when I show the menu and that involves a couple of things.

Already added this on my local so let me know if PR's are welcome.
![menu](https://github.com/macvogelsang/pd-options/assets/1025751/34cd831b-4e39-4898-b24f-c4de65923914)

**Comment by macvogelsang** [comment]
Go ahead and make a PR! That would be much appreciated.

**Comment by gingerbeardman** [comment]
I was also missing this in [Strategies](https://gingerbeardman.itch.io/strategies)! I ended up fudging it for a one level menu, but my hack would not work for multi-level menus (that is, multiple options menus) and I'll also need this for my next little project.

ps: love the googly-eyed gecko!

**Comment by gingerbeardman** [comment]
My workaround was to do some checking in the BButtonUp function of my own input handler

- BButtonDown happens in the Options input handler
- BButtonUp happens in your own handler

**Comment by afk-mario** [comment]
Done, thanks!
