### ISSUE TITLE
Feature: Option style: ACTION

### ISSUE THREAD

**Issue by afk-mario** [macvogelsang/pd-options#12]
It's very useful to be able to run a function when an options is selected, similar to how [the system menu works](https://sdk.play.date/2.0.1/Inside%20Playdate.html#m-menu.addMenuItem).

As a bonus, I think the `Reset to defaults` options could benefit from that as well, a generic `style` definition that  has a `name` and a `callback` and it's called when the options is selected.

**Comment by gingerbeardman** [comment]
This will probably be easier as I've implement a "one-shot" button type of menu item, like Reset but that will close the menu (and in your case do a callback)

**Comment by afk-mario** [comment]
Ah completely missed #5  I think that makes a lot more sense.
